//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorphic.Sensor.Http.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metamorphic.Sensor.Http.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected the HTTP POST request to have a JSON body..
        /// </summary>
        internal static string HttpResponseMessage_ExpectedJsonBody {
            get {
                return ResourceManager.GetString("HttpResponseMessage_ExpectedJsonBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the signal was not specified correctly..
        /// </summary>
        internal static string HttpResponseMessage_MissingSignalType {
            get {
                return ResourceManager.GetString("HttpResponseMessage_MissingSignalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No request information was provided..
        /// </summary>
        internal static string HttpResponseMessage_NoInputStreamDefined {
            get {
                return ResourceManager.GetString("HttpResponseMessage_NoInputStreamDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP POST triggered for /api/jenkins by {0} was not provided with valid data. Body was: {1}.
        /// </summary>
        internal static string Log_Messages_JenkinsController_PostMethodInputDataInvalid_WithOriginAndBody {
            get {
                return ResourceManager.GetString("Log_Messages_JenkinsController_PostMethodInputDataInvalid_WithOriginAndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HTTP POST was triggered for /api/jenkins by {0}.
        /// </summary>
        internal static string Log_Messages_JenkinsController_PostMethodInvoked_WithOrigin {
            get {
                return ResourceManager.GetString("Log_Messages_JenkinsController_PostMethodInvoked_WithOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing signal {0} with parameters ({1}).
        /// </summary>
        internal static string Log_Messages_JenkinsController_PostMethodPublishingSignal_WithSignalInformation {
            get {
                return ResourceManager.GetString("Log_Messages_JenkinsController_PostMethodPublishingSignal_WithSignalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HTTP GET was triggered for /api/signal by {0}.
        /// </summary>
        internal static string Log_Messages_SignalController_GetMethodInvoked_WithOrigin {
            get {
                return ResourceManager.GetString("Log_Messages_SignalController_GetMethodInvoked_WithOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP POST triggered for /api/signal by {0} was not provided with valid data. Body was: {1}.
        /// </summary>
        internal static string Log_Messages_SignalController_PostMethodInputDataInvalid_WithOriginAndBody {
            get {
                return ResourceManager.GetString("Log_Messages_SignalController_PostMethodInputDataInvalid_WithOriginAndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HTTP POST was triggered for /api/signal by {0}.
        /// </summary>
        internal static string Log_Messages_SignalController_PostMethodInvoked_WithOrigin {
            get {
                return ResourceManager.GetString("Log_Messages_SignalController_PostMethodInvoked_WithOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing signal {0} with parameters ({1}).
        /// </summary>
        internal static string Log_Messages_SignalController_PostMethodPublishingSignal_WithSignalInformation {
            get {
                return ResourceManager.GetString("Log_Messages_SignalController_PostMethodPublishingSignal_WithSignalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP POST triggered for /api/tfs by {0} was not provided with valid data. Body was: {1}.
        /// </summary>
        internal static string Log_Messages_TfsController_PostMethodInputDataInvalid_WithOriginAndBody {
            get {
                return ResourceManager.GetString("Log_Messages_TfsController_PostMethodInputDataInvalid_WithOriginAndBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A HTTP POST was triggered for /api/tfs by {0}.
        /// </summary>
        internal static string Log_Messages_TfsController_PostMethodInvoked_WithOrigin {
            get {
                return ResourceManager.GetString("Log_Messages_TfsController_PostMethodInvoked_WithOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing signal {0} with parameters ({1}).
        /// </summary>
        internal static string Log_Messages_TfsController_PostMethodPublishingSignal_WithSignalInformation {
            get {
                return ResourceManager.GetString("Log_Messages_TfsController_PostMethodPublishingSignal_WithSignalInformation", resourceCulture);
            }
        }
    }
}
