//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------
// <copyright company="Nuclei">
//     Copyright 2013 Nuclei. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

namespace Metamorphic.Agent.Nuclei.ExceptionHandling
{
    /// <summary>
    /// Defines the possible exit results for a guarded execution of a method.
    /// </summary>
    internal enum GuardResult
    {
        /// <summary>
        /// There was no exit result. Not normally a valid value.
        /// </summary>
        None,

        /// <summary>
        /// The method executed successfully.
        /// </summary>
        Success,

        /// <summary>
        /// The method execution failed at some point with an unhandled exception.
        /// </summary>
        Failure,
    }
}

