//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------
// <copyright company="Nuclei">
//     Copyright 2013 Nuclei. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

namespace Metamorphic.Server.Nuclei.ExceptionHandling
{
    /// <summary>
    /// Defines a set of event category types used to indicate what category
    /// an event log entry belongs to.
    /// </summary>
    internal enum EventType
    {
        /// <summary>
        /// The event log entry belongs to the exception category.
        /// </summary>
        Exception,
    }
}

