//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------
// <copyright company="Nuclei">
//     Copyright 2013 Nuclei. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

using System;

namespace Metamorphic.Server.Nuclei.ExceptionHandling
{
    /// <summary>
    /// Defines the delegate used for actions that process unhandled exceptions.
    /// </summary>
    /// <param name="exception">The exception to process.</param>
    public delegate void ExceptionProcessor(Exception exception);
}

