//-----------------------------------------------------------------------
// <copyright company="Metamorphic">
//     Copyright 2013 Metamorphic. Licensed under the Apache License, Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

using Metamorphic.Core.Signals;

namespace Metamorphic.Server.Signals
{
    internal interface IGenerateSignals
    {
        /// <summary>
        /// Gets the <see cref="SignalTypeId"/> for the signals generated by the current generator.
        /// </summary>
        SignalTypeId Id
        {
            get;
        }

        /// <summary>
        /// Starts the signal generating process.
        /// </summary>
        void Start();

        /// <summary>
        /// Stops the signal generating process.
        /// </summary>
        void Stop();
    }
}