//-----------------------------------------------------------------------
// <copyright company="Metamorphic">
// Copyright (c) Metamorphic. All rights reserved.
// Licensed under the Apache License, Version 2.0 license. See LICENCE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

using System;
using Metamorphic.Core.Signals;
using Microsoft.Owin.Hosting;

namespace Metamorphic.Server.Signals
{
    internal sealed class WebCallSignalGenerator : IGenerateSignals, IDisposable
    {
        private IDisposable _server;

        /// <summary>
        /// Gets the <see cref="SignalTypeId"/> for the signals generated by the current generator.
        /// </summary>
        public SignalTypeId Id
        {
            get;
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            Stop();
        }

        /// <summary>
        /// Starts the signal generating process.
        /// </summary>
        public void Start()
        {
            var uri = "http://*:7070";
            _server = WebApp.Start<WebCallStartup>(uri);
        }

        /// <summary>
        /// Stops the signal generating process.
        /// </summary>
        public void Stop()
        {
            _server.Dispose();
            _server = null;
        }
    }
}
