//-----------------------------------------------------------------------
// <copyright company="Metamorphic">
// Copyright (c) Metamorphic. All rights reserved.
// Licensed under the Apache License, Version 2.0 license. See LICENCE.md file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

using Metamorphic.Core.Signals;

namespace Metamorphic.Sensor.Http
{
    /// <summary>
    /// Defines the interface for objects that generate signals.
    /// </summary>
    internal interface IGenerateSignals
    {
        /// <summary>
        /// Gets the <see cref="SignalTypeId"/> for the signals generated by the current generator.
        /// </summary>
        SignalTypeId Id
        {
            get;
        }

        /// <summary>
        /// Starts the signal generating process.
        /// </summary>
        void Start();

        /// <summary>
        /// Stops the signal generating process.
        /// </summary>
        void Stop();
    }
}
