//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorphic.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metamorphic.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic.Server action execute AppDomain.
        /// </summary>
        internal static string ActionExecuteDomainName {
            get {
                return ResourceManager.GetString("ActionExecuteDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given rule definition is not valid..
        /// </summary>
        internal static string Exceptions_Messages_InvalidRuleDefinition {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidRuleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given signal does not match the current rule..
        /// </summary>
        internal static string Exceptions_Messages_InvalidSignalForRule {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidSignalForRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; required for the action invocation was missing..
        /// </summary>
        internal static string Exceptions_Messages_MissingActionParameter_WithParameterName {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingActionParameter_WithParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required configuration value is missing. The key for the missing configuration value is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_MissingConfigurationValue_WithKey {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingConfigurationValue_WithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the action type..
        /// </summary>
        internal static string Exceptions_Messages_UnableToLoadActionType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_UnableToLoadActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while processing job with ID {0}. Error was: {1}..
        /// </summary>
        internal static string Log_Messages_RemoteActionExecutor_ProcessJobFailed_WithId_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_RemoteActionExecutor_ProcessJobFailed_WithId_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metamorphic server has started..
        /// </summary>
        internal static string Log_Messages_ServiceStarted {
            get {
                return ResourceManager.GetString("Log_Messages_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metamorphic server has stopped..
        /// </summary>
        internal static string Log_Messages_ServiceStopped {
            get {
                return ResourceManager.GetString("Log_Messages_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating bin directory to store assemblies for packages at {0}..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_CreatingBinDirectory_WithPath {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_CreatingBinDirectory_WithPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while processing jobs. Action with ID {0} could not be found..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessJob_ActionIdNotFound_WithId {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessJob_ActionIdNotFound_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job parameter: Name = {0}; Value = {1}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessJob_ForParameters {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessJob_ForParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing job with ID: {0}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessJob_WithId {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessJob_WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while processing jobs. Error was: {0}..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessJobFailed_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessJobFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal parameter: Name = {0}; Value = {1}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignal_ForParameters {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignal_ForParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing signal of type: {0}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignal_WithType {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignal_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while processing signals. Error was: {0}..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignalsFailed_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignalsFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service that provides the core capabilities for Metamorphic.
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic Server.
        /// </summary>
        internal static string Service_DisplayName {
            get {
                return ResourceManager.GetString("Service_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic.Service.
        /// </summary>
        internal static string Service_ServiceName {
            get {
                return ResourceManager.GetString("Service_ServiceName", resourceCulture);
            }
        }
    }
}
