//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metamorphic.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metamorphic.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The condition type is not valid..
        /// </summary>
        internal static string Exceptions_Messages_InvalidConditionType {
            get {
                return ResourceManager.GetString("Exceptions_Messages_InvalidConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required configuration value is missing. The key for the missing configuration value is: {0}.
        /// </summary>
        internal static string Exceptions_Messages_MissingConfigurationValue_WithKey {
            get {
                return ResourceManager.GetString("Exceptions_Messages_MissingConfigurationValue_WithKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Rule already exists in the collection..
        /// </summary>
        internal static string Exceptions_Messages_RuleAlreadyExists {
            get {
                return ResourceManager.GetString("Exceptions_Messages_RuleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule definition at {0} is not valid..
        /// </summary>
        internal static string Log_Messages_RuleLoader_InvalidRuleDefinition_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_RuleLoader_InvalidRuleDefinition_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered new rule file at: {0}.
        /// </summary>
        internal static string Log_Messages_RuleWatcher_CreatedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_RuleWatcher_CreatedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered removed rule file at: {0}.
        /// </summary>
        internal static string Log_Messages_RuleWatcher_RemovedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_RuleWatcher_RemovedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule discovery - Disabled.
        /// </summary>
        internal static string Log_Messages_RuleWatcher_RuleDiscovery_Disabled {
            get {
                return ResourceManager.GetString("Log_Messages_RuleWatcher_RuleDiscovery_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule discovery - Enabled.
        /// </summary>
        internal static string Log_Messages_RuleWatcher_RuleDiscovery_Enabled {
            get {
                return ResourceManager.GetString("Log_Messages_RuleWatcher_RuleDiscovery_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered updated rule file at: {0}.
        /// </summary>
        internal static string Log_Messages_RuleWatcher_UpdatedFile_WithFilePath {
            get {
                return ResourceManager.GetString("Log_Messages_RuleWatcher_UpdatedFile_WithFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metamorphic server has started..
        /// </summary>
        internal static string Log_Messages_ServiceStarted {
            get {
                return ResourceManager.GetString("Log_Messages_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metamorphic server has stopped..
        /// </summary>
        internal static string Log_Messages_ServiceStopped {
            get {
                return ResourceManager.GetString("Log_Messages_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up worker thread..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_CleaningUpWorker {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_CleaningUpWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new signal was added to the queue, but the processing of signals is turned off. Signal will not be processed..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_NewItemInQueue_ProcessingNotStarted {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_NewItemInQueue_ProcessingNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New item in signal queue. Starting processing thread..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_NewItemInQueue_StartingThread {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_NewItemInQueue_StartingThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new signal was added to the queue. The processing thread is already running. Signal should be processed shortly..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_NewItemInQueue_WorkerAlreadyExists {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_NewItemInQueue_WorkerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal parameter: Name = {0}; Value = {1}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignal_ForParameters {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignal_ForParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing signal of type: {0}.
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignal_WithType {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignal_WithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while processing signals. Error was: {0}..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_ProcessSignalsFailed_WithException {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_ProcessSignalsFailed_WithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal queue empty. Stopping signal processing..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_QueueEmpty {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_QueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting signal processing..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_StartingSignalProcessing {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_StartingSignalProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping processing..
        /// </summary>
        internal static string Log_Messages_SignalProcessor_StoppingProcessing {
            get {
                return ResourceManager.GetString("Log_Messages_SignalProcessor_StoppingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service that provides the core capabilities for Metamorphic.
        /// </summary>
        internal static string Service_Description {
            get {
                return ResourceManager.GetString("Service_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic Server.
        /// </summary>
        internal static string Service_DisplayName {
            get {
                return ResourceManager.GetString("Service_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamorphic.Service.
        /// </summary>
        internal static string Service_ServiceName {
            get {
                return ResourceManager.GetString("Service_ServiceName", resourceCulture);
            }
        }
    }
}
